### ISSUE TITLE
How to load modules?

### ISSUE THREAD

**Issue by vmx** [mikeal/proto.school#6]
How do I load modules in the code?

For #3 I need modules like Buffer, js-multihash and js-cids.

**Comment by mikeal** [comment]
Buffer is a global already. For the rest, in the <script> just use:

```javascript
const CID = require('cids')
const multihash = require('mulithashes')
```

And of course, if they aren't already available use `npm install` to add them and save them in the package.json.

**Comment by vmx** [comment]
I wasn't clear enough. How do I load modules that I want to use in the code that is executed. Imagine a lesson saying "create a CID". There you would need access to `new CID()`.

**Comment by mikeal** [comment]
Ah, ok. I'll need to add a quick feature for that, give me a little bit of time, but the way it will have to work is that you'll need to define the modules available to your lesson and then add the `require` statement to the default code added into the editor.

**Comment by mikeal** [comment]
Added:

1. [pass modules definition to Lesson component.](https://github.com/mikeal/proto.school/blob/master/src/lessons/boiler.vue#L5)
2. [add modules you want available to sample code](https://github.com/mikeal/proto.school/blob/master/src/lessons/boiler.vue#L31)
3. [load available modules](https://github.com/mikeal/proto.school/blob/master/src/lessons/boiler.vue#L31)
4. [include modules in component data](https://github.com/mikeal/proto.school/blob/master/src/lessons/boiler.vue#L39)
